/**
 * Account Validation Utilities for AfriNova
 * Ensures strict uniqueness for Phone Numbers (E.164 normalized) and Email Addresses (case-insensitive).
 */

export function normalizeEmail(email?: string | null): string {
  if (!email) return '';
  return email.trim().toLowerCase();
}

/**
 * Normalizes any raw phone input to E.164 international format (+237677894512).
 *
 * @param rawPhone e.g. "06 77 89 45 12", "+237 677 89 45 12", "00237677894512", "677894512"
 * @param defaultDialCode e.g. "+237"
 */
export function normalizePhoneNumber(rawPhone?: string | null, defaultDialCode: string = '+237'): string {
  if (!rawPhone) return '';

  // Clean dial code: e.g. "+237" -> "237"
  const cleanDialCode = defaultDialCode.replace(/[^0-9]/g, '');

  let cleaned = rawPhone.trim().replace(/[\s\-\(\)\.]/g, '');

  // Handle leading 00 (e.g. 00237...)
  if (cleaned.startsWith('00')) {
    cleaned = '+' + cleaned.slice(2);
  }

  // If already starts with +
  if (cleaned.startsWith('+')) {
    const digitsOnly = cleaned.slice(1).replace(/[^0-9]/g, '');
    return '+' + digitsOnly;
  }

  // Digits only
  let digits = cleaned.replace(/[^0-9]/g, '');

  // Remove leading 0 if present before local number when dial code is supplied (e.g., 0677894512 -> 677894512)
  if (digits.startsWith('0') && cleanDialCode) {
    digits = digits.slice(1);
  }

  // If digits already start with country code (e.g. 237677894512)
  if (cleanDialCode && digits.startsWith(cleanDialCode) && digits.length > cleanDialCode.length + 5) {
    return '+' + digits;
  }

  // Append default dial code
  return '+' + (cleanDialCode || '237') + digits;
}

/**
 * Checks if phone numbers match considering normalized formats.
 */
export function arePhonesEqual(phone1?: string | null, phone2?: string | null, dialCode: string = '+237'): boolean {
  if (!phone1 || !phone2) return false;
  
  const norm1 = normalizePhoneNumber(phone1, dialCode);
  const norm2 = normalizePhoneNumber(phone2, dialCode);

  if (norm1 && norm2 && norm1 === norm2) return true;

  // Fallback: compare significant digit suffixes (last 8-9 digits)
  const digits1 = phone1.replace(/[^0-9]/g, '');
  const digits2 = phone2.replace(/[^0-9]/g, '');
  if (digits1.length >= 8 && digits2.length >= 8) {
    if (digits1 === digits2) return true;
    if (digits1.endsWith(digits2) || digits2.endsWith(digits1)) return true;
  }

  return false;
}

/**
 * Checks if emails match ignoring case and leading/trailing whitespace.
 */
export function areEmailsEqual(email1?: string | null, email2?: string | null): boolean {
  if (!email1 || !email2) return false;
  const norm1 = normalizeEmail(email1);
  const norm2 = normalizeEmail(email2);
  return norm1 !== '' && norm1 === norm2;
}

export interface UniquenessCheckResult {
  isPhoneDuplicate: boolean;
  isEmailDuplicate: boolean;
  errorMessage: string | null;
}

export const PHONE_DUPLICATE_ERROR_MSG = "Ce numéro de téléphone est déjà utilisé par un autre compte. Veuillez vous connecter ou utiliser un autre numéro.";
export const EMAIL_DUPLICATE_ERROR_MSG = "Cette adresse e-mail est déjà utilisée par un autre compte. Veuillez vous connecter ou utiliser une autre adresse e-mail.";

/**
 * Validates uniqueness of phone and email against a list of existing user accounts.
 */
export function checkAccountUniqueness(
  newPhone: string,
  newEmail: string | undefined | null,
  existingUsers: Array<{ phone?: string; email?: string }>,
  dialCode: string = '+237'
): UniquenessCheckResult {
  
  // 1. Check Phone Uniqueness
  if (newPhone) {
    const phoneExists = existingUsers.some(u => arePhonesEqual(newPhone, u.phone, dialCode));
    if (phoneExists) {
      return {
        isPhoneDuplicate: true,
        isEmailDuplicate: false,
        errorMessage: PHONE_DUPLICATE_ERROR_MSG
      };
    }
  }

  // 2. Check Email Uniqueness (Case-Insensitive)
  if (newEmail && newEmail.trim()) {
    const normalizedNewEmail = normalizeEmail(newEmail);
    // Ignore autogenerated phone fallback emails if present, but check real user emails
    const emailExists = existingUsers.some(u => {
      if (!u.email) return false;
      return areEmailsEqual(normalizedNewEmail, u.email);
    });

    if (emailExists) {
      return {
        isPhoneDuplicate: false,
        isEmailDuplicate: true,
        errorMessage: EMAIL_DUPLICATE_ERROR_MSG
      };
    }
  }

  return {
    isPhoneDuplicate: false,
    isEmailDuplicate: false,
    errorMessage: null
  };
}
